---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$USER/public_html/sgsitc.com
    - /bin/mkdir -p $DEPLOYPATH
    - /usr/bin/env npm ci
    - /usr/bin/env npm run build
    - /bin/cp -R out/. $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
